services:
  postgresql:
    container_name: postgresql
    image: postgres
    environment:
      POSTGRES_USER: ayoub
      POSTGRES_PASSWORD: ayoub
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  eureka-server:
    image: ayoub1411/discovery-beta:latest   # Your Eureka server image
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - postgres
    environment:
      - EUREKA_INSTANCE_HOSTNAME=eureka-server
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
  students-service:
    image: ayoub1411/student-beta:latest
    container_name: students-service
    depends_on:
      - eureka-server
      - postgresql
    ports:
      - "8060:8081"
    networks:
      - postgres
    environment:
      EUREKA_HOSTNAME: eureka-server
      EUREKA_URL: http://eureka-server:8761/eureka
      DB_URL: jdbc:postgresql://postgresql:5432/students
      DB_USERNAME: alibou
      DB_PASSWORD: alibou
      SERVER_PORT: 8081
  schools-service:
    image: ayoub1411/school-beta:latest
    container_name: schools-service
    depends_on:
      - eureka-server
      - postgresql
    ports:
      - "8050:8080"
    networks:
      - postgres
    environment:
      EUREKA_HOSTNAME: eureka-server
      EUREKA_URL: http://eureka-server:8761/eureka
      DB_URL: jdbc:postgresql://postgresql:5432/schools
      DB_USERNAME: alibou
      DB_PASSWORD: alibou
      SERVER_PORT: 8080
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped


networks:
  postgres:
    driver: bridge
  zipkin:
    driver: bridge

volumes:
  postgres:
  pgadmin:
